const CONSTANTS = {
  ADD_FORKS: "ADD_FORKS",
  ADD_PULLS: "ADD_PULLS",
  FETCH_USER: "FETCH_USER",
  ADD_USER: "ADD_USER",
  ADD_EVENTS: "ADD_EVENTS",
  FETCH_ERROR: "FETCH_ERROR",
  CLEAR_ERROR: "CLEAR_ERROR",
  FETCH_FORK: "FETCH_FORK",
  ADD_FORK: "ADD_FORK"
}

export default CONSTANTS;
